apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zumble.fullname" . }}
  labels:
    {{- include "zumble.labels" . | nindent 4 }}
data:
  HTTP_API_PASSWORD: {{ .Values.api.password | b64enc }}
