name: Create Release
on: 
  push:
    tags:
    - 'v*'
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
